## SuDoWho v0.1: PseudoKu

<img src="https://imgs.xkcd.com/comics/su_doku.jpg" width="200" height="200" align = "left"/>

In [1]:
import pandas as pd, numpy as np, math
from IPython.display import display,clear_output, Image

In [2]:
#input
df = pd.read_csv('sudoku.csv')

### Preprocessing
1. Transform the input string to array
2. Generate `Rows`, `Cols` and `Blocks` arrays

In [3]:
inp = np.array([int(a) for a in df.iloc[0,0]])

In [4]:
rows = inp.reshape(9,9)

puzzle = np.matrix(rows)

cols = inp.reshape(9,9).T

blocks = np.array([rows[row*3:(row+1)*3,col*3:(col+1)*3] for row in range(3) for col in range(3)])

In [45]:
len(blocks)

9

In [18]:
rows

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [19]:
blocks[]

array([[3, 0, 0],
       [0, 0, 9],
       [0, 6, 0]])

In [57]:
a,b = find_block(0,0)
blocks[(a*3)+b]

array([[0, 0, 4],
       [0, 0, 5],
       [0, 7, 0]])

In [25]:
def find_block(row, col):
    '''Finds the block corresponding to the row and column input'''
    return math.floor(row/3),math.floor(col/3) 



# def generate_possibilities(puzzle):
#     # initiate final results array
#     results = []
    
#     #iterate through each cell
#     for row in range(9):
#         for col in range(9):
#             current = puzzle[row, col]
#             if current != 0:
#                 results.append(current)
#                 continue
#             outcomes = ()
            
#             # iterate through possibilities
#             for i in range(1,10):
                